# Homebrew management Makefile

# Install Homebrew from scratch
install:
	bash install.sh

# Install packages from Brewfile
install-packages:
	brew bundle install

# Dump currently installed packages to Brewfile
dump:
	brew bundle dump --force
